version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: device-postgres
    restart: always
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: device_user
      POSTGRES_PASSWORD: device_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  device-service:
    build: .
    container_name: device-service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devices
      SPRING_DATASOURCE_USERNAME: device_user
      SPRING_DATASOURCE_PASSWORD: device_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8090:8080"

  prometheus:
    image: prom/prometheus
    container_name: device-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - device-service

  grafana:
    image: grafana/grafana
    container_name: device-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: